---
title: "checkP1counts"
author: "JL"
date: "3/28/2018"
output: 
  html_document: 
    keep_md: yes
---




```{r include=FALSE,echo=FALSE}
library(openxlsx)
library(ggplot2)
library(reshape)
library(gridExtra)
library(grid)
library(knitr)

theme_set(theme_bw(10))
t2 <- theme(
    axis.line = element_line(colour = "black"),
    axis.text = element_text(colour = "black"),
    axis.ticks = element_line(colour = "black"),
    panel.grid.major.x = element_blank(),
    panel.grid.minor.x = element_blank(),
    panel.grid.major.y = element_blank(),
    panel.grid.minor.y = element_blank(),
    panel.border = element_blank(),
    panel.background = element_blank(),
    axis.text.x=element_text(angle=90,hjust=1)
)
inDir ="/Volumes/Beta/data/flow/kmeansValidate/results_r26_TcellSubs_Kmeans_wsp_v8/"
outDir="/Volumes/Beta/data/flow/kmeansValidateResults/results_r26_TcellSubs_Kmeans_wsp_v8/"
dir.create(outDir)
summaryFile=paste0(outDir,"summmary.counts.results_r26_TcellSubs_Kmeans_wsp_v8.txt")
corSummaryFile=paste0(outDir,"summmary.cor.results_r26_TcellSubs_Kmeans_wsp_v8.txt")
cvSummaryFile=paste0(outDir,"summmary.cv.results_r26_TcellSubs_Kmeans_wsp_v8.txt")

```


```{r setup, include=FALSE,eval=FALSE}

summFiles <-
  list.files(inDir,
             pattern = "counts.txt$",
             full = TRUE,
             recursive = FALSE)

summaries <- do.call(rbind,lapply(summFiles,read.delim))

map=read.delim("/Volumes/Beta/data/flow/results_r25_25full_SS_SubCD8_SCD14_Manuals/FULL/all.totalCellCounts.metrics.format.txt",
                         stringsAsFactors = FALSE,
                         header = TRUE)
map =map[which(map$PANEL=="panel1"),]
summaries =merge(summaries,map,by.x ="SAMPLE",by.y = "FILE" )

write.table( summaries,file =summaryFile,sep = "\t",quote = FALSE,row.names = FALSE)

```

```{r echo=FALSE,warning=FALSE}
summaries = read.delim(summaryFile,
                       stringsAsFactors = FALSE,
                       header = TRUE)
summaries$SANITIZE_NAME = gsub(" ","_",summaries$SAMPLE)

counts= read.delim("/Volumes/Beta/data/flow/p1CheckCounts/allCounts.xln",
                         stringsAsFactors = FALSE,
                         header = TRUE)

counts= read.xlsx(xlsxFile = "/Users/Kitty/Downloads/p1.final.data (1).xlsx",sheet = 1)
counts=counts[,c(1:55)]

map=read.delim("/Volumes/Beta/data/flow/results_r25_25full_SS_SubCD8_SCD14_Manuals/FULL/all.totalCellCounts.metrics.format.txt",
                         stringsAsFactors = FALSE,
                         header = TRUE)
map =map[which(map$PANEL=="panel1"),]

potFails=counts[which(counts$`effector.helper.Tcells.(CCR7-.CD45RA+).(Comp-BV421-A.(CCR7).v.Comp-BV711-A.(CD45RA))`<1),]$Sample

subP=map$FILE %in% potFails


write.table(map[subP,],file = "/Volumes/Beta/data/flow/p1CheckCounts/allCounts.potential.fails.info.kmean.txt",quote = FALSE,sep = "\t",row.names = FALSE)


OC=read.delim("/Volumes/Beta/data/flow/p1CheckCounts/allCounts.potential.fails.OC.fails.txt",
                         stringsAsFactors = FALSE,
                         header = FALSE)

subP=map$FILE %in% OC$V1
write.table(map[subP,],file = "/Volumes/Beta/data/flow/p1CheckCounts/allCounts.potential.fails.info.OC.txt",quote = FALSE,sep = "\t",row.names = FALSE)





summhelperAll=merge(summaries,counts,by.y="Sample",all.y=TRUE,by.x="SAMPLE")

# helperCM =summaries[which(summaries$POPULATION=="HELPER_central memory"),]

# plot(summhelperCM$,summhelperCM$COUNT)

 ggplot(summhelperAll[which(summhelperAll$POPULATION=="HELPER_central memory"&summhelperAll$HAS_MANUAL_WSP==FALSE),],
                aes(x = `central.memory.helper.Tcells.(CCR7+.CD45RA-).(Comp-BV421-A.(CCR7).v.Comp-BV711-A.(CD45RA))`,
                    y = COUNT,color=HAS_MANUAL_WSP)) +
      geom_point()
 
  ggplot(summhelperAll[which(summhelperAll$POPULATION=="HELPER_naive"&summhelperAll$HAS_MANUAL_WSP==FALSE),],
                aes(x =`naive.helper.Tcells.(CCR7+.CD45RA+).(Comp-BV421-A.(CCR7).v.Comp-BV711-A.(CD45RA))` ,
                    y = COUNT,color=HAS_MANUAL_WSP)) +
      geom_point()
 
  
  ggplot(summhelperAll[which(summhelperAll$POPULATION=="HELPER_effector"&summhelperAll$HAS_MANUAL_WSP==FALSE),],
                aes(x =`effector.helper.Tcells.(CCR7-.CD45RA+).(Comp-BV421-A.(CCR7).v.Comp-BV711-A.(CD45RA))` ,
                    y = COUNT,color=HAS_MANUAL_WSP)) +
      geom_point()
  
    ggplot(summhelperAll[which(summhelperAll$POPULATION=="HELPER_effector memory"&summhelperAll$HAS_MANUAL_WSP==FALSE),],
                aes(x =`effector.memory.helper.Tcells.(CCR7-.CD45RA-).(Comp-BV421-A.(CCR7).v.Comp-BV711-A.(CD45RA))` ,
                    y = COUNT,color=HAS_MANUAL_WSP)) +
      geom_point()
  
    
    
    
    ggplot(summhelperAll[which(summhelperAll$POPULATION=="CYTO_central memory"&summhelperAll$HAS_MANUAL_WSP==FALSE),],
                aes(x = `central.memory.cytotoxic.Tcells.(CCR7+.,.CD45RA-).(Comp-BV421-A.(CCR7).v.Comp-BV711-A.(CD45RA))`,
                    y = COUNT,color=HAS_MANUAL_WSP)) +
      geom_point()
 
  ggplot(summhelperAll[which(summhelperAll$POPULATION=="CYTO_naive"&summhelperAll$HAS_MANUAL_WSP==FALSE),],
                aes(x =`naive.cytotoxic.Tcells.(CCR7+.,.CD45RA+).(Comp-BV421-A.(CCR7).v.Comp-BV711-A.(CD45RA))` ,
                    y = COUNT,color=HAS_MANUAL_WSP)) +
      geom_point()
 
  
  ggplot(summhelperAll[which(summhelperAll$POPULATION=="CYTO_effector"&summhelperAll$HAS_MANUAL_WSP==FALSE),],
                aes(x =`effector.cytotoxic.Tcells.(CCR7-.CD45RA+).(Comp-BV421-A.(CCR7).v.Comp-BV711-A.(CD45RA))` ,
                    y = COUNT,color=HAS_MANUAL_WSP)) +
      geom_point()
  
    ggplot(summhelperAll[which(summhelperAll$POPULATION=="CYTO_effector memory"&summhelperAll$HAS_MANUAL_WSP==FALSE),],
                aes(x =`effector.memory.cytotoxic.Tcells.(CCR7-.,.CD45RA-).(Comp-BV421-A.(CCR7).v.Comp-BV711-A.(CD45RA))` ,
                    y = COUNT,color=HAS_MANUAL_WSP)) +
      geom_point()

 
    
    
    
    
    
 ggplot(summhelperAll[which(summhelperAll$POPULATION=="HELPER_central memory"&summhelperAll$HAS_MANUAL_WSP==FALSE),],
                aes(x = `central.memory.helper.Tcells.(CCR7+.CD45RA-).(Comp-BV421-A.(CCR7).v.Comp-BV711-A.(CD45RA))`,
                    y = COUNT,color=HAS_MANUAL_WSP)) +
      geom_point()+xlim(0,100)+ylim(0,100)
 
  ggplot(summhelperAll[which(summhelperAll$POPULATION=="HELPER_naive"&summhelperAll$HAS_MANUAL_WSP==FALSE),],
                aes(x =`naive.helper.Tcells.(CCR7+.CD45RA+).(Comp-BV421-A.(CCR7).v.Comp-BV711-A.(CD45RA))` ,
                    y = COUNT,color=HAS_MANUAL_WSP)) +
      geom_point()+xlim(0,100)+ylim(0,100)
 
  
  ggplot(summhelperAll[which(summhelperAll$POPULATION=="HELPER_effector"&summhelperAll$HAS_MANUAL_WSP==FALSE),],
                aes(x =`effector.helper.Tcells.(CCR7-.CD45RA+).(Comp-BV421-A.(CCR7).v.Comp-BV711-A.(CD45RA))` ,
                    y = COUNT,color=HAS_MANUAL_WSP)) +
      geom_point()+xlim(0,100)+ylim(0,100)
  
    ggplot(summhelperAll[which(summhelperAll$POPULATION=="HELPER_effector memory"&summhelperAll$HAS_MANUAL_WSP==FALSE),],
                aes(x =`effector.memory.helper.Tcells.(CCR7-.CD45RA-).(Comp-BV421-A.(CCR7).v.Comp-BV711-A.(CD45RA))` ,
                    y = COUNT,color=HAS_MANUAL_WSP)) +
      geom_point()+xlim(0,100)+ylim(0,100)
  
    
    
    
    ggplot(summhelperAll[which(summhelperAll$POPULATION=="CYTO_central memory"&summhelperAll$HAS_MANUAL_WSP==FALSE),],
                aes(x = `central.memory.cytotoxic.Tcells.(CCR7+.,.CD45RA-).(Comp-BV421-A.(CCR7).v.Comp-BV711-A.(CD45RA))`,
                    y = COUNT,color=HAS_MANUAL_WSP)) +
      geom_point()+xlim(0,100)+ylim(0,100)
 
  ggplot(summhelperAll[which(summhelperAll$POPULATION=="CYTO_naive"&summhelperAll$HAS_MANUAL_WSP==FALSE),],
                aes(x =`naive.cytotoxic.Tcells.(CCR7+.,.CD45RA+).(Comp-BV421-A.(CCR7).v.Comp-BV711-A.(CD45RA))` ,
                    y = COUNT,color=HAS_MANUAL_WSP)) +
      geom_point()+xlim(0,100)+ylim(0,100)
 
  
  ggplot(summhelperAll[which(summhelperAll$POPULATION=="CYTO_effector"&summhelperAll$HAS_MANUAL_WSP==FALSE),],
                aes(x =`effector.cytotoxic.Tcells.(CCR7-.CD45RA+).(Comp-BV421-A.(CCR7).v.Comp-BV711-A.(CD45RA))` ,
                    y = COUNT,color=HAS_MANUAL_WSP)) +
      geom_point()+xlim(0,100)+ylim(0,100)
  
    ggplot(summhelperAll[which(summhelperAll$POPULATION=="CYTO_effector memory"&summhelperAll$HAS_MANUAL_WSP==FALSE),],
                aes(x =`effector.memory.cytotoxic.Tcells.(CCR7-.,.CD45RA-).(Comp-BV421-A.(CCR7).v.Comp-BV711-A.(CD45RA))` ,
                    y = COUNT,color=HAS_MANUAL_WSP)) +
      geom_point()+xlim(0,100)+ylim(0,100)

    
       
```


<!--     interest=c("central.memory.helper.Tcells..CCR7..CD45RA....Comp.BV421.A..CCR7..v.Comp.BV711.A..CD45RA..", -->
<!-- "naive.helper.Tcells..CCR7..CD45RA....Comp.BV421.A..CCR7..v.Comp.BV711.A..CD45RA..", -->
<!-- "effector.helper.Tcells..CCR7..CD45RA....Comp.BV421.A..CCR7..v.Comp.BV711.A..CD45RA..", -->
<!-- "effector.memory.helper.Tcells..CCR7..CD45RA....Comp.BV421.A..CCR7..v.Comp.BV711.A..CD45RA..", -->
<!-- "central.memory.cytotoxic.Tcells..CCR7....CD45RA....Comp.BV421.A..CCR7..v.Comp.BV711.A..CD45RA..", -->
<!-- "naive.cytotoxic.Tcells..CCR7....CD45RA....Comp.BV421.A..CCR7..v.Comp.BV711.A..CD45RA..", -->
<!-- "effector.cytotoxic.Tcells...CCR7...CD45RA....Comp.BV421.A..CCR7..v.Comp.BV711.A..CD45RA..", -->
<!-- "effector.memory.cytotoxic.Tcells..CCR7....CD45RA....Comp.BV421.A..CCR7..v.Comp.BV711.A..CD45RA..") -->

<!--     for(inter in interest){ -->
<!--       print(paste(inter," HELPER")) -->
<!--       print(table(counts[,inter]<counts$Helper.Tcells.CD4...Comp.APC.Cy7.A..CD4..v.Comp.BUV396.A..CD8..,counts$HAS_MANUAL_WSP)) -->
<!--     print(paste(inter," Cyto")) -->
<!--      print(table(counts[,inter]<counts$cytotoxic.Tcells.CD8...Comp.APC.Cy7.A..CD4..v.Comp.BUV396.A..CD8..,counts$HAS_MANUAL_WSP)) -->

<!--     } -->

```{r sesstup, echo=FALSE,eval=TRUE}

latest=    read.xlsx(xlsxFile = "/Users/Kitty/Downloads/p1.final.data (1).xlsx",sheet = 1)

hrs=    read.xlsx(xlsxFile = "/Volumes/Beta/data/flow/HRS1000 REPORT.xlsx",sheet = 1)

latest=latest[,c(1:17,57:79)]
colnames(sub)

for(col in colnames(latest)){
  print(col)
  print(max(na.omit(as.numeric(latest[,col]))))
}

latest$KEY=latest$LAB_ID
hrs$KEY=hrs$Study.ID
merge=merge(latest,hrs,by.x = "KEY",by.y ="KEY" )

merge=merge[which(merge$`IgD+MemB`<=100&merge$`IgD-MemB`<=100),]

# colnames(hrs) %in% colnames(latest)
mergeNoMan=merge[which(merge$HAS_MANUAL_WSP==FALSE),]
write.table(counts[which(counts$`effector.helper.Tcells.(CCR7-.CD45RA+).(Comp-BV421-A.(CCR7).v.Comp-BV711-A.(CD45RA))`<1),]$Sample,file = "/Volumes/Beta/data/flow/p1CheckCounts/allCounts.potential.fails.txt",quote = FALSE,row.names = FALSE)
map = list(c(
  "B.cells.(CD3-.CD19+).(Comp-APC-A.(CD3).v.Comp-PE-Cy7-A.(CD19))",
  "Bcell"
  ),c(
  "Tcells.(CD3+.CD19-).(Comp-APC-A.(CD3).v.Comp-PE-Cy7-A.(CD19))",
  "Tcell"
  ),c(
  "Helper.Tcells-CD4+.(Comp-APC-Cy7-A.(CD4).v.Comp-BUV396-A.(CD8))",
  "HT"
  ),c(
  "cytotoxic.Tcells-CD8+.(Comp-APC-Cy7-A.(CD4).v.Comp-BUV396-A.(CD8))",
  "CT"
  ),c(
  "IgD+.memory.Bcells.(CD27+).(Comp-BUV737-A.(IgD).v.Comp-FITC-A.(CD27))",
  "IgD+MemB"
  ),c(
  "IgD-.memory.Bcells.(CD27+).(Comp-BUV737-A.(IgD).v.Comp-FITC-A.(CD27))",
  "IgD-MemB"
  ),c(
  "naive.Bcells.(CD27-.IgD+).(Comp-BUV737-A.(IgD).v.Comp-FITC-A.(CD27))",
  "NaiveB"
  ),c(
  "effector.helper.Tcells.(CCR7-.CD45RA+).(Comp-BV421-A.(CCR7).v.Comp-BV711-A.(CD45RA))",
  "E.HT"
  )
  ,c(
  "effector.memory.helper.Tcells.(CCR7-.CD45RA-).(Comp-BV421-A.(CCR7).v.Comp-BV711-A.(CD45RA))",
  "EM.HT"
  ),c(
  "central.memory.helper.Tcells.(CCR7+.CD45RA-).(Comp-BV421-A.(CCR7).v.Comp-BV711-A.(CD45RA))",
  "CM.HT"
  ),c(
  "naive.helper.Tcells.(CCR7+.CD45RA+).(Comp-BV421-A.(CCR7).v.Comp-BV711-A.(CD45RA))",
  "N.HT"
  ),c(
  "effector.cytotoxic.Tcells.(CCR7-.CD45RA+).(Comp-BV421-A.(CCR7).v.Comp-BV711-A.(CD45RA))",
  "E.CT"
  )
  ,c(
  "effector.memory.cytotoxic.Tcells.(CCR7-.,.CD45RA-).(Comp-BV421-A.(CCR7).v.Comp-BV711-A.(CD45RA))",
  "EM.CT"
  ),c(
  "central.memory.cytotoxic.Tcells.(CCR7+.,.CD45RA-).(Comp-BV421-A.(CCR7).v.Comp-BV711-A.(CD45RA))",
  "CM.CT"
  ),c(
  "naive.cytotoxic.Tcells.(CCR7+.,.CD45RA+).(Comp-BV421-A.(CCR7).v.Comp-BV711-A.(CD45RA))",
  "N.CT"
  )


  )

for(pop in map){
  print(pop)
  co =cor.test(merge[,pop[2]] ,merge[,pop[1]] )
  mergeMan=merge[which(merge$HAS_MANUAL_WSP==FALSE),]
  coMan =cor.test(mergeMan[,pop[2]] ,mergeMan[,pop[1]] )

  mergeOC=merge[which(merge$HAS_MANUAL_WSP==FALSE),]
  coOC =cor.test(mergeOC[,pop[2]] ,mergeOC[,pop[1]] )

  t = ggplot(merge,
             aes(x = merge[, pop[2]] ,
             y = merge[, pop[1]], color = Source)) +
             geom_point() + xlab(paste0("1st 1K ", pop[2])) + facet_wrap(~ HAS_MANUAL_WSP) +
             ggtitle(
             paste0(
             # "cor All=",
             # co$estimate,
             # "\ncor manaul v 1k manual=",
             coMan$estimate,
             "\ncor OC v 1k manual=",
             coOC$estimate
             )
             )
             print(t)
}





```

