---
title: "Manual_Auto"
author: "JL"
date: "1/8/2018"
output: html_document
---
```{r}

dir="/Volumes/Beta/data/flow/results_r25_22full_SS_SubCD8_SCD14_Manuals_partialTest/"

parsePanel <- function(metrics,freqMetrics, map, panel){
  metricsPanel=metrics[which(metrics$Panel==panel&metrics$GATE=="MANUAL"),]
  # map$ManualOriginal=map$Manual
  map$Manual=gsub("/","_",map$Manual)
  map$Auto="NA"
  map=unique(map)
  metricsPanel=merge(metricsPanel,map,by.x="Population",by.y="Manual")
  metricsPanel$Manual=metricsPanel$Population
  # metricsPanel$nameOriginal=metricsPanel$name
  metricsPanel$name=gsub(".fcs_.*",".fcs",metricsPanel$name)
  freqMetricsPanel=freqMetrics[which(freqMetrics$Panel==panel&freqMetrics$GATE=="AUTOMATIC"),]
  freqMetricsPanel$Auto=freqMetricsPanel$Population
  freqMetricsPanel=freqMetricsPanel[,colnames(metricsPanel)]
  
  keepAuto=!(freqMetricsPanel$name %in% metricsPanel$name)
  autoMetrics = freqMetricsPanel[keepAuto,]
  
  combo = rbind(autoMetrics,metricsPanel)
  
  return(combo)
}

```



```{r setup, include=FALSE,eval=FALSE}
library(openxlsx)
p1mapD = read.delim("/Users/Kitty/git/auto-fcs/explore/openCyto/panel1Map.txt", stringsAsFactors = FALSE, sep = "\t")
p2mapD = read.delim("/Users/Kitty/git/auto-fcs/explore/openCyto/panel2Map.txt", stringsAsFactors = FALSE, sep = "\t")
  

latestAuto = read.delim(paste0(dir,"all.freq.metrics.txt"), stringsAsFactors = FALSE)

latestManual = read.delim(paste0(dir,"all.metrics.txt"), stringsAsFactors = FALSE)

panel1=parsePanel(metrics = latestManual,freqMetrics = latestAuto,map = p1mapD,panel = "panel1")
panel2=parsePanel(metrics = latestManual,freqMetrics = latestAuto,map = p2mapD,panel = "panel2")

panels=rbind(panel1,panel2)

panels$LAB_ID=NA
panels[which(is.na(panels$Manual)),]$Population
 

manifest=read.xlsx("/Volumes/Beta/data/flow/HRS sample list.xlsx")
manifest$PANEL_1_OC_FILE_ATTEMPTED=NA
manifest$PANEL_2_OC_FILE_ATTEMPTED=NA
num=0
for(id in manifest$Lab.ID){
  match=grep(paste0("_",id,"_"),panels$name)
  # print(match)
  num=num+1
  print(num)
  if(length(match)>0){
    # print(length(match))
    panels[match,]$LAB_ID=id
    sub=panels[match,]
    p1=sub[which(sub$PANEL=="panel1"),]
    p2=sub[which(sub$PANEL=="panel2"),]
      if (length(p1[, 1]) > 0) {
      panels[which(panels$Lab.ID == id), ]$PANEL_1_OC_FILE_ATTEMPTED = paste(p1$FILE,collapse = ";")

    }
    if (length(p2[, 1]) > 0) {
    panels[which(panels$Lab.ID == id), ]$PANEL_2_OC_FILE_ATTEMPTED = paste(p2$FILE,collapse = ";")

    }
  }
}

panels$DATE=gsub(" .*","",panels$name)
panels$DATE=gsub("_PANEL","",panels$DATE)
panels$Manual=gsub("/","_",panels$Manual)

# regexpr("\\.[^\\.]*$", x)
  write.table(
    panels,
    sep = "\t",
    quote = FALSE,
    file = paste0(dir,"all.freq.metrics.use.txt"),
    row.names = FALSE
  ) 
save(panels,file =paste0(dir,"all.freq.metrics.use.Rdata" ))

```


```{r}
library(reshape2)

load(paste0(dir,"all.freq.metrics.use.Rdata" ))

print(panels$name[duplicated(paste0(panels$name,panels$Population))])

print(panels$name[duplicated(paste0(panels$name,panels$Manual))])
print(panels[which(panels=="panel1"),]$name[duplicated(paste0(panels$Lab.ID))])
print(panels[which(panels=="panel2"),]$name[duplicated(paste0(panels$Lab.ID))])


aggregatePanel <- function(panelData){

panelDataCast =dcast(data = panelData,formula = name~Manual,fun.aggregate=sum,value.var = "Count")

}

p1Trim=panels[which(panels=="panel1"),c("name","Manual","Count")]
p1Cast=aggregatePanel(panelData = p1Trim)


```



