---
title: "TrendQC"
author: "JL"
date: "1/12/2018"
output: 
  html_document: 
    keep_md: yes
---
```{r include=TRUE,fig.height=10,fig.width=12,echo=FALSE}

dir = "/Volumes/Beta/data/flow/results_r25_25full_SS_SubCD8_SCD14_Manuals/finalCounts/"

# allC = merge(p1C,p2C,by.x="Sample",by.y="Sample")
popsOfInterestFile="/Volumes/Beta/data/flow/results_r25_25full_SS_SubCD8_SCD14_Manuals/finalCounts/popsOfInterest.txt"

popsOfInterest=read.delim(popsOfInterestFile, stringsAsFactors = FALSE, sep = "\t")
popsOfInterest$POPC=gsub(" ",".",popsOfInterest$POPC)
popsOfInterest$POPF=gsub(" ",".",popsOfInterest$POPF)

```

# Trends by population
- removed samples that did not match to a Lab ID from the "FLOW ONLY" tab of "HRS sample list.xlsx"
- removed samples where date could not be parsed
- removed samples where EXPERIMENTER could not be parsed




```{r setup, include=TRUE,fig.height=10,fig.width=12,echo=FALSE,eval=FALSE}
library(openxlsx)

source("/Users/Kitty/git/auto-fcs/explore/openCyto/TrendQC/nameFormat.R")


tcFile="/Volumes/Beta/data/flow/results_r25_25full_SS_SubCD8_SCD14_Manuals/FULL/all.totalCellCounts.metrics.txt"
tc=read.delim(tcFile, stringsAsFactors = FALSE, sep = "\t")


manifest=read.xlsx("/Volumes/Beta/data/flow/HRS sample list.xlsx")
num=0
tc$LAB_ID=NA

for(id in manifest$Lab.ID){
  match=grep(paste0("_",id,"_"),tc$FILE,fixed = TRUE)
  # print(match)
  num=num+1
  print(num)
# 
  if(length(match)>0){
    # print(length(match))
    tc[match,]$LAB_ID=id

  }
}

parseDF <- function(frame,popsOfInterest,tc,PopColumn) {
  frame = frame[,c(colnames(frame) %in% c("Sample",popsOfInterest[,c(PopColumn)]))]
  frame=parseDate(frame = frame,nameColumn = "Sample")
  frame=parseExperimenter(frame = frame,nameColumn = "Sample")
  frame=merge(frame,tc,by.x = "FILE",by.y = "FILE",all.x = "TRUE")
  frame = frame[which(!is.na(frame$LAB_ID)),]
  frame$EXPERIMENTER_MACHINE=paste0(frame$EXPERIMENTER,"_",frame$MACHINE)
  miss=!(popsOfInterest[,c(PopColumn)] %in% c(colnames(frame)))
  print(table(miss))
  return(frame)

}

finals="/Volumes/Beta/data/flow/results_r25_25full_SS_SubCD8_SCD14_Manuals/finalCounts/xln/finals.xlsx"

p1C= read.xlsx(finals, sheet=2)
p2C= read.xlsx(finals, sheet=4)


p1F= read.xlsx(finals, sheet=1)
p2F= read.xlsx(finals, sheet=3)

p1C=parseDF(frame=p1C,popsOfInterest = popsOfInterest ,tc=tc,PopColumn="POPC")
p2C=parseDF(frame=p2C,popsOfInterest = popsOfInterest ,tc=tc,PopColumn="POPC")
p1F=parseDF(frame=p1F,popsOfInterest = popsOfInterest ,tc=tc,PopColumn="POPF")
p2F=parseDF(frame=p2F,popsOfInterest = popsOfInterest ,tc=tc,PopColumn="POPF")

table(miss)


save(p1C,file=paste0(dir,"all.p1.cnts_fixed.format.Rdata"))
save(p2C,file=paste0(dir,"all.p2.cnts_fixed.format.Rdata"))
save(p1F,file=paste0(dir,"all.p1.freqs.format.Rdata"))
save(p2F,file=paste0(dir,"all.p2.freq.format.Rdata"))


tc=parseDate(frame = tc,nameColumn = "FILE",removeNA=FALSE)
tc=parseExperimenter(frame = tc,nameColumn = "FILE",removeNA=FALSE)


# latest=merge(latest,nameMatch,by.y="name",by.x="name")

save(tc,file="/Volumes/Beta/data/flow/results_r25_25full_SS_SubCD8_SCD14_Manuals/FULL/all.totalCellCounts.metrics.format.RData")


write.table(
   tc,
    sep = "\t",
    quote = FALSE,
    file ="/Volumes/Beta/data/flow/results_r25_25full_SS_SubCD8_SCD14_Manuals/FULL/all.totalCellCounts.metrics.format.txt",
    row.names = FALSE
  ) 



# 

# pb=ggplot(tc,aes(x=as.factor(DATE_MONTH),y=TOTAL_COUNTS,colour=PANEL_MACHINE)) +
#   geom_boxplot() +
#   xlab("Month processed") +
#   ylab("Total events in file")+t2
#   print(pb)
```


```{r fig.height=10,fig.width=12,echo=FALSE,warning=FALSE}

load(file=paste0(dir,"all.p1.cnts_fixed.format.Rdata"))
load(file=paste0(dir,"all.p2.cnts_fixed.format.Rdata"))
load(file=paste0(dir,"all.p1.freqs.format.Rdata"))
load(file=paste0(dir,"all.p2.freq.format.Rdata"))

popsOfInterest$UseP1 = (popsOfInterest$POPC %in% colnames(p1C))

library(ggplot2)
library(knitr)
t2 <- theme(
  axis.line = element_line(colour = "black"),
  axis.text = element_text(colour = "black"),
  axis.ticks = element_line(colour = "black"),
  # panel.grid.major.x = element_blank(),
  panel.grid.minor.x = element_blank(),
  # panel.grid.major.y = element_blank(),
  # panel.grid.minor.y = element_blank(),
  panel.border = element_blank(),
  # panel.background = element_blank(),
  # legend.position="none",
  axis.text.x = element_text(angle = 90, hjust = 1)
)
theme_set(theme_grey(base_size = 18))



for (pop in unique(popsOfInterest$POPC)) {
  colC=popsOfInterest[which(popsOfInterest$POPC==pop),]$POPC
  colF=popsOfInterest[which(popsOfInterest$POPC==pop),]$POPF

  if(popsOfInterest[which(popsOfInterest$POPC==pop),]$UseP1){
  subC = p1C
  subF = p1F

  }else{
  subC = p2C
  subF = p2F


  }
  print(pop)
  print(paste0("n=",length(subC$FILE)))
  print(paste0("PLOT TYPE = Machine Time COUNT"))

  pb = ggplot(subC,
              aes(
                x = as.factor(DATE_MONTH),
                y = as.numeric(subC[,colC]),
                colour = MACHINE
              )) +
    geom_boxplot() +
    xlab("Month processed") +
    ylab(paste0("Total events in ",pop)) + t2+ggtitle(paste0("Pop=",pop))
  print(pb)
  print(kable(as.data.frame(table(subC$EXPERIMENTER)),format="markdown"))

   pb = ggplot(subC,
              aes(
                x = as.factor(DATE_MONTH),
                y = as.numeric(subC[,colC]),
                colour = EXPERIMENTER
              )) +
    geom_boxplot() +
    xlab("Month processed") +
    ylab(paste0("Total events in ",pop)) + t2+ggtitle(paste0("Pop=",pop))
  print(pb)
  
  
  
  
  
  print(pop)
  print(paste0("n=",length(subC$FILE)))
  print(paste0("PLOT TYPE = Machine Time FREQ"))

  if(!is.na(colF)){
  pb = ggplot(subF,
              aes(
                x = as.factor(DATE_MONTH),
                y = as.numeric(subF[,colF]),
                colour = MACHINE
              )) +
    geom_boxplot() +
    xlab("Month processed") +
    ylab(paste0("FreqParent  ",pop)) + t2+ggtitle(paste0("Pop=",pop))
  print(pb)
  
   pb = ggplot(subF,
              aes(
                x = as.factor(DATE_MONTH),
                y = as.numeric(subF[,colF]),
                colour = EXPERIMENTER
              )) +
    geom_boxplot() +
    xlab("Month processed") +
    ylab(paste0("FreqParent  ",pop)) + t2+ggtitle(paste0("Pop=",pop))
  print(pb)
  
   pb = ggplot(subF,
              aes(
                x = reorder(EXPERIMENTER_MACHINE, subF[,colF], FUN = median),
                y = as.numeric(subF[,colF]),
                colour = EXPERIMENTER_MACHINE
              )) +
    geom_boxplot() +
    xlab("Experiment - Machine") +
    ylab(paste0("FreqParent  ",pop)) + t2+ggtitle(paste0("Pop=",pop))
  print(pb)
  
formula <- TOTAL_COUNTS ~ DATE_MONTH + MACHINE + PANEL + EXPERIMENTER

lm <- lm(formula, tc)
summary(lm)



library(MASS)
fit <- lm(formula,data=tc)
step <- stepAIC(fit, direction="both")
step$anova
  
  
  
  }else{
      print(paste0("NA for Freq plot"))
  }
}
# 
# for (exp in unique(popsOfInterest$EXPERIMENTER)) {
#   sub = popsOfInterest[which(popsOfInterest$EXPERIMENTER == exp),]
#   pb = ggplot(sub,
#               aes(
#                 x = as.factor(DATE_MONTH),
#                 y = TOTAL_COUNTS,
#                 colour = PANEL_MACHINE
#               )) +
#     geom_boxplot() +
#     xlab("Month processed") +
#     ylab("Total events in file") + t2 + ggtitle(paste0("EXPERIMENTER = ", exp))
#   print(pb)
# }
# 
# 
# for (machine in unique(popsOfInterest$MACHINE)) {
#   for (panel in unique(popsOfInterest$PANEL)) {
#     sub = popsOfInterest[which(popsOfInterest$MACHINE == machine&popsOfInterest$PANEL==panel),]
#     
#     pb = ggplot(sub,
#                 aes(
#                   x = reorder(EXPERIMENTER, TOTAL_COUNTS, FUN = median),
#                   y = TOTAL_COUNTS,
#                   colour = EXPERIMENTER
#                 )) +
#       geom_boxplot() +
#       xlab("Month processed") +
#       ylab("Total events in file") + t2+ ggtitle(paste0("PANEL=", panel,"\nMACHINE=",machine, "\nORDER=MEDIAN"))
#     print(pb)
#     
#     pb = ggplot(sub,
#                 aes(
#                   x = reorder(EXPERIMENTER, TOTAL_COUNTS, FUN = mad),
#                   y = TOTAL_COUNTS,
#                   colour = EXPERIMENTER
#                 )) +
#       geom_boxplot() +
#       xlab("Month processed") +
#       ylab("Total events in file") + t2+ ggtitle(paste0("PANEL=", panel,"\nMACHINE=",machine, "\nORDER=MAD"))
#     print(pb)
#     formula <- TOTAL_COUNTS ~  EXPERIMENTER
#     lm <- lm(formula, sub)
#     print(summary(lm))
#     
#     fit <- aov(formula, data=sub)
#     print(TukeyHSD(fit))
#   }
# }
# 
# 
# formula <- TOTAL_COUNTS ~ DATE_MONTH + MACHINE + PANEL + EXPERIMENTER
# lm <- lm(formula, popsOfInterest)
# summary(lm)
# 
# 
# 
# library(MASS)
# fit <- lm(formula,data=popsOfInterest)
# step <- stepAIC(fit, direction="both")
# step$anova
# 
# write.table(
#   popsOfInterest,
#   file =
#     paste0(dir,"all.totalCellCounts.metrics.txt.format.txt"),
#   row.names = FALSE,
#   quote = FALSE,
#   sep = "\t"
# )


```

