#!/usr/bin/env bash

FILES="/home/thyagara/shared/HRS/UPLOAD\ FCS\ HRS\ samples/*/*.fcs"
for f in $FILES
do
	echo "Processing $f"
done


FILES="/home/thyagara/shared/HRS/UPLOAD FCS HRS samples/" 
cd 
find . -type f -name '*.fcs' -exec cp -n -v -t /scratch.global/lanej/flow/full/fcs2/ {} \;
find . -type f -name '*.fcs' -exec rsync -a {} /scratch.global/lanej/flow/full/fcs2/  \;


rsync -av --include='*/' --include='*.fcs' --exclude='*' "$FILES" /scratch.global/lanej/flow/full/fcs/




FILES="/home/thyagara/shared/HRS/UPLOAD FCS HRS samples/" 
cd "$FILES"
find . -type f -name '*.fcs' -exec rsync -av {} /scratch.global/lanej/flow/full/fcs/  \; >/scratch.global/lanej/flow/rsync3.log


find . -type f -name '*.fcs' -exec rsync -av {} /scratch.global/lanej/flow/full/fcs/  \; 

find . -type f -name "*PANEL 1*" -exec mv {} ./panel1 \;
find . -type f -name "*PANEL 2*" -exec mv {} ./panel2 \; 



find . -type f -name "*Rename.wsp" -exec diff {} /scratch.global/lanej/flow/full/results_r25_25full_SS_SubCD8_SCD14_Manuals/TEST_TCELLS/{} \; |grep -i lymph


find . -type f -name "*Rename.wsp" -exec diff {} /scratch.global/lanej/flow/full/results_r25_25full_SS_SubCD8_SCD14_Manuals/FULL/{} \; |grep -i lymph



find . -type f -name *Rename.wsp  |wc -l
find . -type f -name "*Rename.wsp" -exec diff {} /scratch.global/lanej/flow/full/results_r25_25full_SS_SubCD8_SCD14_Manuals/TEST_TCELLS/{} \; &> diff.txt
grep -i lymph diff.txt


find . -type f -name p1.pcts.xln -exec wc -l {} \;
find . -type f -name p2.pcts.xln -exec wc -l {} \;

find ./*/gatesRename/ -type f -name "*Rename.wsp"  |grep "panel1Rename.wsp" |wc -l

wc -l ./*/panel1Counts/p1.cnts.xln
wc -l ./*/panel2Counts/p2.cnts.xln





find . -type f -name *Rename.wsp  |wc -l
find . -type f -name "*Rename.wsp" -exec diff {} /scratch.global/lanej/flow/full/results_r25_25full_SS_SubCD8_SCD14_Manuals/FULL/{} \; &> diff.txt
grep -i lymph diff.txt


 for file in *Rename*.wsp; do    diff "$file" "/scratch.global/lanej/flow/full/results_r25_25full_SS_SubCD8_SCD14_Manuals/FULL/*/gates/$file" ; done


find . -type f -name  | sed -e 's,^\./,,' > deploy.txt


find . -type f -name "*Rename.wsp" -exec diff {} "/scratch.global/lanej/flow/full/results_r25_25full_SS_SubCD8_SCD14_Manuals/FULL/*/gates/{}" \; &> diff.txt



find . -type f -name "*Rename.wsp" -exec diff {} "/scratch.global/lanej/flow/full/results_r25_25full_SS_SubCD8_SCD14_Manuals/FULL/*/gates/{}" \; &> diff.txt


/scratch.global/lanej/flow/full/results_ensure/Validate/all


 for file in *Rename*.wsp; do    echo "$file" ; done


  for file in ./*/gates/*Rename*.wsp; do
      name=`basename "$file" .bar`

      diff /scratch.global/lanej/flow/full/results_ensure/Validate/all/"$name" "$file" &>> ~/diffTest.txt
      echo "$name" >> ~/diffTest.txt
      echo "$file" ; done
     

