#!/usr/bin/env bash

FILES="/home/thyagara/shared/HRS/UPLOAD\ FCS\ HRS\ samples/*/*.fcs"
for f in $FILES
do
	echo "Processing $f"
done


FILES="/home/thyagara/shared/HRS/UPLOAD FCS HRS samples/" 
cd 
find . -type f -name '*.fcs' -exec cp -n -v -t /scratch.global/lanej/flow/full/fcs2/ {} \;
find . -type f -name '*.fcs' -exec rsync -a {} /scratch.global/lanej/flow/full/fcs2/  \;


rsync -av --include='*/' --include='*.fcs' --exclude='*' "$FILES" /scratch.global/lanej/flow/full/fcs/




FILES="/home/thyagara/shared/HRS/UPLOAD FCS HRS samples/" 
cd "$FILES"
find . -type f -name '*.fcs' -exec rsync -av {} /scratch.global/lanej/flow/full/fcs/  \; >/scratch.global/lanej/flow/rsync3.log


find . -type f -name '*.fcs' -exec rsync -av {} /scratch.global/lanej/flow/full/fcs/  \; 

find . -type f -name "*PANEL 1*" -exec mv {} ./panel1 \;
find . -type f -name "*PANEL 2*" -exec mv {} ./panel2 \; 



find . -type f -name "*Rename.wsp" -exec diff {} /scratch.global/lanej/flow/full/results_r25_25full_SS_SubCD8_SCD14_Manuals/TEST_TCELLS/{} \; |grep -i lymph


find . -type f -name "*Rename.wsp" -exec diff {} /scratch.global/lanej/flow/full/results_r25_25full_SS_SubCD8_SCD14_Manuals/FULL/{} \; |grep -i lymph



find . -type f -name *Rename.wsp  |wc -l
find . -type f -name "*Rename.wsp" -exec diff {} /scratch.global/lanej/flow/full/results_r25_25full_SS_SubCD8_SCD14_Manuals/TEST_TCELLS/{} \; |grep -i lymph &> diff.txt
grep -i lymph diff.txt




