---
title: "SummaryClusters"
author: "JL"
date: "7/17/2018"
output: ioslides_presentation
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(superheat)
library(scales)
library(plotly)
library(knitr)
library(ClusterR)

theme_set(theme_bw(15))

markersToCluster = c("CD27",
"CD28",
"CD95",
"CCR7",
"CD45RA",
"CD8",
"CD4",
"CD3",
"CD19",
"IgD",
"HLA.DR")

populations =    c(
"central.memory",
"naive",
"effector.memory",
"EM1",
"EM2",
"EM3",
"EM4",
"effector",
"E",
"pE1",
"pE2"
)

markersToCluster = rev(markersToCluster)


manuals = read.delim(
  "/Volumes/Beta/data/flow/kmeansValidateResults/results_r26_TcellSubs_Kmeans_wsp_v8/r26_v3_Manual_Samples.txt",
  stringsAsFactors = FALSE,
  header = FALSE
)

mapFull=read.delim("/Volumes/Beta/data/flow/results_r25_25full_SS_SubCD8_SCD14_Manuals/FULL/all.totalCellCounts.metrics.format.txt",
                         stringsAsFactors = FALSE,
                         header = TRUE)

map=mapFull  
# lsr =map[which(map$MACHINE=="LSR"),]   
map =map[which(map$PANEL=="panel1"),]
map =map[which(!is.na(map$LAB_ID)),]

summary = read.delim(
  "/Volumes/Beta2/flow/testSummary/allSummaries.txt" ,
  stringsAsFactors = FALSE,
  header = TRUE
  )


summary$SAMPLE = summary$SAMPLE_RAW_SCALE_CENTROID
summary$SANITIZE_NAME = gsub(" ", "_", summary$SAMPLE)


summary$MANUAL_ANNOTATION = summary$SANITIZE_NAME %in% manuals$V1

summary = summary[which(summary$MANUAL_ANNOTATION == FALSE),]

summary$CTL = gsub(".*Ctl-|.*CTL-|.*Ctl_|.*Clt-|.*Ctl|.*Ctl- |.*Ctl ",
"",
summary$SAMPLE)
summary$CTL = gsub("_.*", "", summary$CTL)
summary$CTL = gsub(" .*", "", summary$CTL)
summary = summary[order(summary$CTL), ]

getHeat <- function(sub) {
  superheat(
      as.matrix(t(sub)),
      
      # place dendrograms on columns and rows
      row.dendrogram = T,
      col.dendrogram = T,
      
      # make gridlines white for enhanced prettiness
      grid.hline.col = "white",
      grid.vline.col = "white",
      # membership.rows = markersToCluster,
      
      # rotate bottom label text
      bottom.label.text.angle = 90
    )
}


```

## Raw centroids

```{r fig.width=9}

sub = summary[, paste0(markersToCluster,"_RAW_SCALE_CENTROID")]
colnames(sub)=markersToCluster
getHeat(sub=sub)
```

- median value of markers in each cluster

## Normalized centroids

```{r fig.width=9}

sub = summary[, paste0(markersToCluster,"_SCALED_CENTROID")]
colnames(sub)=markersToCluster
getHeat(sub=sub)

```

- median z-score of markers in each cluster


## Freq cluster

```{r fig.width=9}

sub = summary[, paste0(populations,"_ClusterFreq")]
colnames(sub)=populations
getHeat(sub=sub)

```

- median z-score of markers in each cluster


## Freq population

```{r fig.width=9}

sub = summary[, paste0(populations,"_TotalFreq")]
colnames(sub)=populations
getHeat(sub=sub)

```

- median z-score of markers in each cluster

