---
title: "SummaryClusters"
author: "JL"
date: "7/19/2018"
output: ioslides_presentation
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
knitr::opts_chunk$set(message = FALSE)
knitr::opts_chunk$set(warning = FALSE)

library(superheat)
library(scales)
library(plotly)
library(knitr)
library(ClusterR)
library(cytofkit)


# source("./")
theme_set(theme_bw(15))

markersToCluster = c("CD27",
"CD28",
"CD95",
"CCR7",
"CD45RA",
"CD8",
"CD4",
"CD3",
"CD19",
"IgD",
"HLA.DR")

populations =    c(
"central.memory",
"naive",
"effector.memory",
"EM1",
"EM2",
"EM3",
"EM4",
"effector",
"E",
"pE1",
"pE2",
"CD28P_27M"
)

markersToCluster = rev(markersToCluster)
```

```{r prep, include=FALSE, eval=TRUE}

manuals = read.delim(
  "/Volumes/Beta/data/flow/kmeansValidateResults/results_r26_TcellSubs_Kmeans_wsp_v8/r26_v3_Manual_Samples.txt",
  stringsAsFactors = FALSE,
  header = FALSE
)

mapFull=read.delim("/Volumes/Beta/data/flow/results_r25_25full_SS_SubCD8_SCD14_Manuals/FULL/all.totalCellCounts.metrics.format.txt",
                         stringsAsFactors = FALSE,
                         header = TRUE)

map=mapFull  
# lsr =map[which(map$MACHINE=="LSR"),]   
map =map[which(map$PANEL=="panel1"),]
map=map[,c("FILE","TOTAL_COUNTS","PANEL","MACHINE","EXPERIMENTER","LAB_ID")]
# map =map[which(!is.na(map$LAB_ID)),]

summary = read.delim(
  "/Volumes/Beta2/flow/detect_NoNorm_v6_lymph_Mem_summary/allSummaries.txt" ,
  stringsAsFactors = FALSE,
  header = TRUE,check.names = FALSE
  )


summary$SAMPLE = summary$SAMPLE_RAW_CENTROID
summary$SANITIZE_NAME = gsub(" ", "_", summary$SAMPLE)

summary=merge(summary,map,by.x ="SAMPLE",by.y ="FILE",all.x = TRUE)

# summary$MANUAL_ANNOTATION = 

summary = summary[!(summary$SANITIZE_NAME %in% manuals$V1),]

summary$CTL = gsub(".*Ctl-|.*CTL-|.*Ctl_|.*Clt-|.*Ctl|.*Ctl- |.*Ctl ",
"",
summary$SAMPLE)
summary$CTL = gsub("_.*", "", summary$CTL)
summary$CTL = gsub(" .*", "", summary$CTL)
summary$CTL=gsub("-.*", "", summary$CTL)

summary$CTL=gsub("2016", "STUDY_SAMPLE", summary$CTL)
summary$CTL=gsub("2017", "STUDY_SAMPLE", summary$CTL)
summary$CTL=gsub("Specimen", "Specimen", summary$CTL)

ctls=c("A","B","C","D","E","F","G","H")
# summary = summary[order(summary$CTL), ]
use=(!is.na(summary$LAB_ID) |summary$CTL %in% ctls)
summary=summary[use,]
# summary=summary[1:10000,]
save(summary,file="summary.RData")
```


```{r}

load("summary.RData")

# nms <- names(summary)
# raw=nms[grepl(pattern = "_RAW", nms)]
# raw=gsub("_SCALE","",raw)
# 
# colnames(summary)[grepl(pattern = "_RAW", colnames(summary))]=raw


# tmp=unique(summary[,c("SAMPLE_RAW_CENTROID","MACHINE")])
# table(tmp$MACHINE)
getHeat <- function(sub) {
  # superheat(
  #     as.matrix(t(sub)),
  # 
  #     # place dendrograms on columns and rows
  #     row.dendrogram = T,
  #     col.dendrogram = T,
  # 
  #     # make gridlines white for enhanced prettiness
  #     grid.hline.col = "white",
  #     grid.vline.col = "white",
  #     # membership.rows = markersToCluster,
  # 
  #     # rotate bottom label text
  #     bottom.label.text.angle = 90
  #   )
}


```


```{r fig.width=9}

summary=summary[which(summary$MACHINE=="LSR"),]

```

- ordered by machine, using only LSR for remaining



## Meta Phenograph +Meta tsne

```{r fig.width=9,message=FALSE}
type="_SCALED_CENTROID"
sub = summary[, paste0(markersToCluster, type)]
colnames(sub) = markersToCluster
clustFile= paste0("clusterPhenograph",type,".RData")
tsneFile=paste0("tsne",type,".RData")
```

```{r fig.width=9,message=FALSE,eval=TRUE}
clusterPhenograph = cytof_cluster(xdata = sub, method = "Rphenograph")
tsne <- cytof_dimReduction(data=sub, method = "tsne",out_dim = 2)

# save(clusterPhenograph,file = clustFile)
# save(tsne,file =tsneFile)

```

```{r fig.width=7,message=FALSE}
# load(clustFile)
# load(tsneFile)

summary$META_CLUSTER =clusterPhenograph
summary$META_CLUSTER =as.numeric(summary$META_CLUSTER )
summary$metaTsne1=tsne[,1]
summary$metaTsne2 = tsne[, 2]


nms=names(summary)
metaName = nms[grepl(pattern = "_BASE_MINUS_CLUST", nms)]
metaName = metaName[!grepl(pattern = "RAW", metaName)]
metaName = metaName[!grepl(pattern = "MEM_LABEL", metaName)]

metaMEM = aggregate(summary[, metaName],
                                 list(summary$PHENOGRAPH),
                                 median)

markersMEM=gsub("MEM_","",nms)
markersMEM=gsub("_BASE_MINUS_CLUST","",markersMEM)

# results$MEM_ROUND = round(results$MEM)
#   addPlus = results$MEM_ROUND >= 0
#   results$MEM_ROUND[addPlus] = paste0("+", results$MEM_ROUND[addPlus])
#   results$MEM_LABEL = paste0(results$MARKER, results$MEM_ROUND)

metaMEM$META_MEM_LABEL=""


colnames(metaMEM)=paste0("META_",colnames(metaMEM))



gz1 <- gzfile(paste0("summary.meta.mem.gz"), "w")
    write.table(
      metaMEM,
      file = gz1 ,
      sep = "\t",
      quote = FALSE,
      row.names = FALSE
    )
close(gz1)

summary=merge(summary,metaMEM,by.x ="META_CLUSTER",by.y ="META_Group.1",all.x = TRUE)


metaMEM = aggregate(summary[, metaName],
                                 list(summary$PHENOGRAPH),
                                 mad)

colnames(metaMEM)=paste0("META_MAD_",colnames(metaMEM))
summary=merge(summary,metaMEM,by.x ="META_CLUSTER",by.y ="META_MAD_Group.1",all.x = TRUE)



# aggregate(summary,"META_CLUSTER+MEM_CD27_BASE_MINUS_CLUST",FUN = median,na.rm=TRUE)
myColor <- rev(RColorBrewer::brewer.pal(11, "Spectral"))



```


```{r fig.width=7,message=FALSE}

gz1 <- gzfile(paste0("summary.gz"), "w")
    write.table(
      summary,
      file = gz1 ,
      sep = "\t",
      quote = FALSE,
      row.names = FALSE
    )
close(gz1)

cols=data.frame(COLUMN=colnames(summary))
rownames(cols)=cols$COLUMN
cols$DESCRIPTION="NA"

for(pop in populations){
  popForm=pop
  # gsub("."," ",pop,fixed = TRUE)
  cols[popForm,"DESCRIPTION"] = paste0("Count of ",pop, " events in this phenograph cluster")
  
  popTFreq=paste0(popForm,"_TotalFreq")
  cols[popTFreq,"DESCRIPTION"] = paste0("Proportion of events in this phenograph cluster out of all events in  ",pop)
 
  popCFreq=paste0(popForm,"_ClusterFreq")
  cols[popCFreq,"DESCRIPTION"] = paste0("Frequency of population ",pop, " in this phenograph cluster")
   
}

for(marker in markersToCluster){
  mraw = paste0(marker, "_RAW_CENTROID")
  cols[mraw, "DESCRIPTION"] = paste0(
  "Median raw (but after compensating/logicle transform) expression of ",
  marker,
  "in this phenograph cluster"
  )
  
  mscale = paste0(marker, "_SCALED_CENTROID")
  cols[mscale, "DESCRIPTION"] = paste0(
  "Median scaled (after compensating/logicle transform and normalizing) expression of ",
  marker,
  "in this phenograph cluster"
  )
  # MEM_RAW_CD45RA_BASE_MINUS_CLUST
  mem1 = paste0("MEM_", marker, "_BASE_MINUS_CLUST")
  cols[mem1, "DESCRIPTION"] = paste0(
  "mem score using method a of https://media.nature.com/original/nature-assets/nmeth/journal/v14/n3/extref/nmeth.4149-S1.pdf ",
  marker,
  "in this phenograph cluster"
  )
  
}

cols["PHENOGRAPH_CLUSTER","DESCRIPTION"]="Phenograph cluster for the sample"
cols["TOTAL_PHENOGRAPH_COUNTS","DESCRIPTION"]="Total events in sample's phenograph cluster"
cols["SAMPLE_SCALED_CENTROID","DESCRIPTION"]="Sample used for centroids (just a check)"
cols["SAMPLE_RAW_CENTROID","DESCRIPTION"]="Sample used for centroids (just a check)"
cols["SAMPLE_RAW_CENTROID","DESCRIPTION"]="Sample used for centroids (just a check)"
cols["SAMPLE","DESCRIPTION"]="Sample name"
cols["SANITIZE_NAME","DESCRIPTION"]="Sample with spaces replaced with _"
cols["CTL","DESCRIPTION"]="Which control this sample is"
cols["META_CLUSTER","DESCRIPTION"]="The phenograph meta-cluster this sample belongs to"
cols["metaTsne1","DESCRIPTION"]="Meta-tsne diminsion 1"
cols["metaTsne2","DESCRIPTION"]="Meta-tsne diminsion 2"
cols["TOTAL_COUNTS","DESCRIPTION"]="Total events in fcs file"
cols["PANEL","DESCRIPTION"]="flow panel"
cols["MACHINE","DESCRIPTION"]="LSR or FORTESSA"
cols["EXPERIMENTER","DESCRIPTION"]="EXPERIMENTER"
cols["LAB_ID","DESCRIPTION"]="LAB ID for this sample"


write.table(
cols,
file = "summary.columns" ,
sep = "\t",
quote = FALSE,
row.names = FALSE
)

metaMap =summary[,c("SAMPLE","PHENOGRAPH_CLUSTER","META_CLUSTER")]

write.table(
  metaMap,
  file = "summary.metaMap" ,
  sep = "\t",
  quote = FALSE,
  row.names = FALSE
)

# metaMapSub=metaMap[metaMap$META_CLUSTER %in% subs,]
# 
# write.table(
#   metaMapSub,
#   file = paste0("subs_",paste0(subs,collapse="_"),"_summary.naive.interest.metaMap" ),
#   sep = "\t",
#   quote = FALSE,
#   row.names = FALSE
# )


require(openxlsx)
list_of_datasets <- list("DATA_DICTIONARY" = cols, "SUMMARY" = summary,"META_MAP"=metaMap)
write.xlsx(list_of_datasets, file = "summary.xlsx")

save(summary,file ="summary.meta.RData")


```

