---
title: "Example"
author: "JL"
date: "7/20/2018"
output: html_document
---

## Example workflow
1. Select "Tsne Plots"
1. Color middle tsne plot by "naive_ClusterFreq" to see which meta clusters are naive cells
2. Meta clusters 1, 2, 8, 9, and 16 seem to be made up of mostly naive cells (less so 8)
3. Select meta clusters 1, 2, 8, 9, and 16 in the "Meta clusters to characterize" dropdown
4. Select "Raw Heatmap" to see which markers differentiate these meta-clusters
  - Seems to be IgD, CD95, CD19, maybe CD4
5. Similar process for "Normalized Heatmap"
6. Select "Distributions" to see box-plot comparisons of marker expression 


### Current Methods


1. Run phenograph on each individual sample, starting with cytotoxic T cells
2. For each sample's phenograph cluster compute:
  1.  median compensated/transformed expression across all markers used (calling this "RAW")
  2.  median of the normalized (mean 0, SD 1) compensated/transformed expression across all markers use
  3. Frequency of known cytotoxic subsets in the cluster
  4.  Proportion of events in the phenograph cluster out of all events in each known cytotoxic subset
3. Combine individual sample's centroids into a single matrix
4. Run phenograph on the combined matrix (currently using "RAW")
5. Run tsne on the combined matrix (currently using "RAW")
6. Plot results, coloring by things