---
title: "Count"
author: "JL"
date: "12/22/2017"
output: 
  html_document: 
    keep_md: yes
---

```{r setup}
allOrig = read.delim("/Users/Kitty/git/auto-fcs/explore/openCyto/annoCounts/r25_panel2.txt", stringsAsFactors = FALSE,header = FALSE,sep = "|")
allOrig$V1=gsub("\t","",allOrig$V1)
allOrig$KEY=paste0(allOrig$V1,allOrig$V2)
allOrig$V3=gsub("Manual","manual",allOrig$V3)
nonCtl =!grepl("Ctl",allOrig$V2)
allOrig=allOrig[nonCtl,]
singleCells  = read.delim("/Users/Kitty/git/auto-fcs/explore/openCyto/annoCounts/singlecellbranch.txt", stringsAsFactors = FALSE,header = FALSE,sep = "|")
singleCells$V1=gsub("\t","",singleCells$V1)

singleCells$V3=gsub("Manual","manual",singleCells$V3)
singleCellsNOTMANUAL =singleCells[which(singleCells$V3!="Manual"&singleCells$V3 !="manual"),]
singleCellsNOTMANUAL$KEY=paste0(singleCellsNOTMANUAL$V1,singleCellsNOTMANUAL$V2)

notFixed=!allOrig$KEY %in% singleCellsNOTMANUAL$KEY

allOrigStillProbs=allOrig[notFixed,]


```


#Pre singlet correction

```{r }




library(knitr)
kable(as.data.frame(table(allOrig$V1,allOrig$V3)),format = "markdown")


```

#Post singlet correction

```{r }
kable(as.data.frame(table(allOrigStillProbs$V1,allOrigStillProbs$V3)),format = "markdown")


CD14 = allOrigStillProbs[which(allOrigStillProbs$V1=="CD14-"),]


```

