---
title: "Validate TCell subset adjustments"
author: "JL"
date: "01/15/2017"
output: 
  html_document: 
    keep_md: yes
---

```{r setup, include=FALSE}
library(knitr)

library(ggplot2)
t2 <- theme(
  axis.line = element_line(colour = "black"),
  axis.text = element_text(colour = "black"),
  axis.ticks = element_line(colour = "black"),
  # panel.grid.major.x = element_blank(),
  panel.grid.minor.x = element_blank(),
  # panel.grid.major.y = element_blank(),
  # panel.grid.minor.y = element_blank(),
  panel.border = element_blank(),
  # panel.background = element_blank(),
  # legend.position="none",
  axis.text.x=element_text(angle=90,hjust=1)
)
theme_set(theme_grey(base_size = 18)) 

manual=read.delim("/Volumes/Beta/data/flow/results_r25_22full_SS_SubCD8_SCD14_Manuals_partialTest/manual", stringsAsFactors = FALSE,header = FALSE)

rand = read.delim("/Volumes/Beta/data/flow/results_r25_17full/all.freq.metrics.txt", stringsAsFactors = FALSE)
rand$TEMPLATE_FILE_USED="NA"
# cd8=read.delim("/Volumes/Beta/data/flow/results_r25_20full_SS_SubCD8/all.freq.metrics.txt", stringsAsFactors = FALSE)
  
cd8Files=read.delim("/Users/Kitty/git/auto-fcs/explore/openCyto/CD_8_quads.txt", stringsAsFactors = FALSE,header = FALSE) 
# use=cd8$name %in% cd8Files$V1
# cd8Use=cd8[use,]

noUse=!(rand$name %in% cd8Files$V1)
rand=rand[noUse,]


# rand=rbind(cd8Use,randUse)

# results_r25_20full_SS_SubCD8
rand$KEY=paste0(rand$name,rand$Population,rand$Panel,rand$Parent,rand$MACHINE,rand$Manual)



reg= read.delim("/Volumes/Beta/data/flow/results_r25_25full_SS_SubCD8_SCD14_Manuals/FULL/all.freq.metrics.txt", stringsAsFactors = FALSE)
reg$KEY=paste0(reg$name,reg$Population,reg$Panel,reg$Parent,reg$MACHINE,reg$Manual)
use=!(reg$name %in% manual$V1)
reg=reg[use,]

table(reg$KEY %in% rand$KEY)
reg$TEMPLATE_FILE_USEDTRIM =gsub(".*/","",reg$TEMPLATE_FILE_USED)
reg$TEMPLATE_FILE_USEDTRIM =gsub(".dev","",reg$TEMPLATE_FILE_USEDTRIM)
reg$TEMPLATE_FILE_USEDTRIM =gsub(".txt","",reg$TEMPLATE_FILE_USEDTRIM)


# rand$TEMPLATE_FILE_USEDTRIM =gsub(".*/","",rand$TEMPLATE_FILE_USED)
# rand$TEMPLATE_FILE_USEDTRIM =gsub(".dev","",rand$TEMPLATE_FILE_USEDTRIM)
# rand$TEMPLATE_FILE_USEDTRIM =gsub(".txt","",rand$TEMPLATE_FILE_USEDTRIM)

combo=merge(reg,rand,by.x = "KEY",by.y = "KEY")

```


# Frequency of parent counts (> 0% difference)

```{r  echo=FALSE,warning=FALSE}

comboP1=combo
comboP1$DIFF=abs(comboP1$freqParent.x-comboP1$freqParent.y)
comboP1=comboP1[which(comboP1$DIFF>0&comboP1$Panel.x=="panel1"),]


pbf = ggplot(comboP1, aes(
  x = freqParent.x,
  y = freqParent.y,colour= Population.x )) +
  geom_point() +
  xlab(paste0("Previous freq parent")) +
  ylab(paste0("Adjusted TCell subs freq parent")) + t2+xlim(0,1)+ylim(0,1) 
pbf
pbf = ggplot(comboP1, aes(
  x = freqParent.x,
  y = freqParent.y,colour= RealAutoParent.x )) +
  geom_point() +
  xlab(paste0("Previous freq parent, n gates")) +
  ylab(paste0("Adjusted TCell subs  freq parent")) + t2+xlim(0,1)+ylim(0,1) 
pbf

write.table(
  comboP1,
  file =
  "/Volumes/Beta/data/flow/results_r25_25full_SS_SubCD8_SCD14_Manuals/FULL/all.freq.metrics.allDiff.txt",
  row.names = FALSE,
  quote = FALSE,
  sep = "\t"
  )


comboP1=combo
comboP1$DIFF=abs(comboP1$Count.x-comboP1$Count.y)/comboP1$Count.x
comboP1=comboP1[which(comboP1$DIFF>0.01&comboP1$Panel.x=="panel1"),]


pbf = ggplot(comboP1, aes(
  x = freqParent.x,
  y = freqParent.y,colour= Population.x )) +
  geom_point() +
  xlab(paste0("Previous freq parent")) +
  ylab(paste0("Adjusted TCell subs freq parent")) + t2+xlim(0,1)+ylim(0,1) 
pbf
pbf = ggplot(comboP1, aes(
  x = freqParent.x,
  y = freqParent.y,colour= RealAutoParent.x )) +
  geom_point() +
  xlab(paste0("Previous freq parent, n gates")) +
  ylab(paste0("Adjusted TCell subs  freq parent")) + t2+xlim(0,1)+ylim(0,1) 
pbf

write.table(
  comboP1,
  file =
  "/Volumes/Beta/data/flow/results_r25_25full_SS_SubCD8_SCD14_Manuals/FULL/all.freq.metrics.allDiff.txt",
  row.names = FALSE,
  quote = FALSE,
  sep = "\t"
)




```



```{r  echo=FALSE}

# kable(comboP1[c("name.x","RealAutoParent.x","Manual.x","freqParent.x","freqParent.y")],format = "markdown")

```
