---
title: "KmeansEval - manual correlations and control comparisons "
author: "JL"
date: "2/16/2018"
output: 
  html_document: 
    keep_md: yes
---

Comparing global metrics (population median etc) between kmeans and manual

```{r include=FALSE,echo=FALSE}
library(openxlsx)
library(ggplot2)
library(reshape)


theme_set(theme_bw(10))
t2 <- theme(
    axis.line = element_line(colour = "black"),
    axis.text = element_text(colour = "black"),
    axis.ticks = element_line(colour = "black"),
    panel.grid.major.x = element_blank(),
    panel.grid.minor.x = element_blank(),
    panel.grid.major.y = element_blank(),
    panel.grid.minor.y = element_blank(),
    panel.border = element_blank(),
    panel.background = element_blank(),
    axis.text.x=element_text(angle=90,hjust=1)
)
inDir ="/Volumes/Beta/data/flow/kmeansValidate/results_r26_TcellSubs_v4"
outDir="/Volumes/Beta/data/flow/kmeansValidateResults/results_r26_TcellSubs_v4/"
dir.create(outDir)
summaryFile=paste0(outDir,"summmary.counts.results_r26_TcellSubs_v4.txt")
corSummaryFile=paste0(outDir,"summmary.cor.results_r26_TcellSubs_v4.txt")

```


```{r setup, include=FALSE,eval=FALSE}

summFiles <-
  list.files(inDir,
             pattern = "counts.txt$",
             full = TRUE,
             recursive = FALSE)

summaries <- do.call(rbind,lapply(summFiles,read.delim))

map=read.delim("/Volumes/Beta/data/flow/results_r25_25full_SS_SubCD8_SCD14_Manuals/FULL/all.totalCellCounts.metrics.format.txt",
                         stringsAsFactors = FALSE,
                         header = TRUE)
map =map[which(map$PANEL=="panel1"),]
summaries =merge(summaries,map,by.x ="SAMPLE",by.y = "FILE" )

write.table( summaries,file =summaryFile,sep = "\t",quote = FALSE,row.names = FALSE)

```

```{r echo=FALSE,warning=FALSE,fig.height=8,fig.width=10}
summaries = read.delim(summaryFile,
                       stringsAsFactors = FALSE,
                       header = TRUE)
excludes = unique(summaries[which(summaries$NUM_POPS_ASSIGNED!=4),]$SAMPLE)
summaries=summaries[which(summaries$NUM_POPS_ASSIGNED==4),]

# l = summaries[which(summaries$POPULATION=="CYTO_effector"&&summaries$COUNT<1000),]
# summaries[which(summaries$SAMPLE=="2016-11-17_PANEL 1_ZF_Group one_F1652905_004.fcs"),]

summaries$OPTIMAL_K = as.factor(summaries$OPTIMAL_K)
summaries$POPULATION = as.factor(summaries$POPULATION)
summaries$PARENT_FREQ = (summaries$COUNT * 100) / summaries$PARENT_COUNT
summaries = summaries[which(!is.na(summaries$PARENT_FREQ)), ]

# summaries$POPULATION=gsub("CYTO_effector memory_CD28M_CD27M","pE cytotoxic Tcells (CD27-  CD28-)",summaries$POPULATION)
# summaries$POPULATION=gsub("CYTO_effector memory_CD28P_CD27P","pE1 cytotoxic Tcells (CD27+  CD28+)",summaries$POPULATION)
# summaries$POPULATION=gsub("CYTO_effector memory_CD28M_CD27P","pE2 cytotoxic Tcells (CD27+ , CD28-)",summaries$POPULATION)
# 
# summaries$POPULATION=gsub("CYTO_effector_CD28P_CD27P","EM1 cytotoxic Tcells (CD27+  CD28+)",summaries$POPULATION)
# summaries$POPULATION=gsub("CYTO_effector_CD28M_CD27P","EM2 cytotoxic Tcells (CD27+  CD28-)",summaries$POPULATION)
# summaries$POPULATION=gsub("CYTO_effector_CD28M_CD27M","EM3 cytotoxic Tcells (CD27-  CD28-)",summaries$POPULATION)
# summaries$POPULATION=gsub("CYTO_effector_CD28P_CD27M","EM4 cytotoxic Tcells (CD27-  CD28+)",summaries$POPULATION)

summaries$KEY = paste0(summaries$LAB_ID, "_", summaries$POPULATION)
summaries$KEYFCS = paste0(summaries$SAMPLE, "_", summaries$POPULATION)

trim = !grepl("CD28",summaries$POPULATION)
summariesTrim=summaries[trim,]
summariesTrimC0=summariesTrim[which(summariesTrim$COUNT==0),]
counts =as.data.frame(table(summariesTrimC0$SAMPLE,summariesTrimC0$COUNT))
sub= counts[which(counts$Var2==0),]
keep =!(summaries$SAMPLE %in% sub$Var1)
rid =(summaries$SAMPLE %in% sub$Var1)


excludes = unique(c(excludes, summaries[rid, ]$SAMPLE))
write.table(
  data.frame(
    EXCLUDE_SAMPLE = excludes,
    EXCLUDE_SAMPLE_SANITIZE = gsub(" ", "_", excludes)
  ),
  file = paste0(summaryFile, ".exclude.txt"),
  sep = "\t",
  quote = FALSE,
  row.names = FALSE
)


# summaries=summaries[keep,]



```


```{r echo=FALSE,warning=FALSE,fig.height=8,fig.width=10,eval=TRUE}
ctlCounts1 = read.xlsx("/Volumes/Beta/data/flow/controlValidate/manulacontrolcounts.xlsx", sheet =1)
ctlCounts2 = read.xlsx("/Volumes/Beta/data/flow/controlValidate/remainingcontrolsforOCcomp.xlsx", sheet =1)
colnames(ctlCounts2)[1]=colnames(ctlCounts1)[1]
ctlCounts=rbind(ctlCounts1,ctlCounts2)

interestCtls = c(
  "FCS.ID",
  "CM.CT" ,
  "EFF.CT" ,
  "EFF.MEM.CT",
  "NAÏVE.CT",
  "CM.HT" ,
   "EFF.HT",
   "EFF.MEM.HT" ,
  "NAÏVE.HT" 

  )
interestCtls = ctlCounts[, interestCtls]
colnames(interestCtls) = c(
  "Study.ID",
  "CYTO_central memory" ,
  "CYTO_effector" ,
  "CYTO_effector memory",
  "CYTO_naive",
  "HELPER_central memory" ,
  "HELPER_effector",
  "HELPER_effector memory" ,
  "HELPER_naive"
)


interestCtlsM =  melt(interestCtls, id.vars = "Study.ID")
interestCtlsM$KEY = paste0(interestCtlsM$Study.ID, "_", interestCtlsM$variable)
comboCtls = merge(summaries,
              interestCtlsM,
              by.x = "KEYFCS",
              by.y = "KEY")
pops = unique(comboCtls$POPULATION)


corSummary = data.frame()

compVar="COUNT"
for (pop in pops) {
  plotData = comboCtls[which(comboCtls$POPULATION == pop), ]
  cor1 = cor.test(
    as.numeric(plotData[,compVar]),
    as.numeric(plotData$value),
    method = "pearson",
    na.action = "na.omit"
  )
  cor2 = cor.test(
    as.numeric(plotData[,compVar]),
    as.numeric(plotData$value),
    method = "spearman",
    na.action = "na.omit"
  )
  
  g1 = ggplot(plotData,
              aes(x = plotData[,compVar],
                  y = value, color = OPTIMAL_K)) +
    geom_point() +
    xlab(paste0("KMEANS percent parent")) +
    ylab(paste0("Manual percent parent")) + t2 + ggtitle(
      paste0(
        pop,
        "\npearson=",
        cor1$estimate,
        "\nspearman=",
        cor2$estimate,
        "\nN=",
        length(plotData$KEY)
      )
    )  +
    theme(legend.position = "bottom")
  
  print(g1)
  
  tmp = data.frame(
    POPULATION = pop,
    METRIC = "PARENT_FREQ",
    PEARSON = cor1$estimate,
    SPEARMAN = cor2$estimate
  )
  corSummary = rbind(corSummary, tmp)
}

```




```{r echo=FALSE,warning=FALSE,fig.height=8,fig.width=10,eval=FALSE}

summaries = summaries[which(!is.na(summaries$LAB_ID)), ]

ggplot(summariesTrim, aes(
  x = reorder(summariesTrim$POPULATION, PARENT_FREQ, FUN = median),
  y = PARENT_FREQ,
  colour = POPULATION
)) +
  xlab(paste0("Population")) +
  ylab(paste0("Percent Parent")) + t2 +
  geom_boxplot() + ggtitle("Kmeans clustering") + ylim(0, 100)

origPercents = read.xlsx("/Volumes/Beta/data/flow/HRS1000 REPORT.xlsx", sheet =
                           1)
interest = c(
  "Study.ID",
  "CM.CT" ,
  "E.CT" ,
  "EM.CT",
  "N.CT",
  "CM.HT" ,
  "E.HT",
  "EM.HT" ,
  "N.HT"

  )
 
  # "pE.CT",
  # "pE1.CT",
  # "pE2.CT",
  # "EM1.C.T",
  # "EM2.CT",
  # "EM3.CT",
  # "EM4.CT"

interestPercents = origPercents[, interest]
colnames(interestPercents) = c(
  "Study.ID",
  "CYTO_central memory" ,
  "CYTO_effector" ,
  "CYTO_effector memory",
  "CYTO_naive",
  "HELPER_central memory" ,
  "HELPER_effector",
  "HELPER_effector memory" ,
  "HELPER_naive"
)
  # "pE cytotoxic Tcells (CD27-  CD28-)",
  # "pE1 cytotoxic Tcells (CD27+  CD28+)",
  # "pE2 cytotoxic Tcells (CD27+ , CD28-)",
  # "EM1 cytotoxic Tcells (CD27+  CD28+)",
  # "EM2 cytotoxic Tcells (CD27+  CD28-)",
  # "EM3 cytotoxic Tcells (CD27-  CD28-)",
  # "EM4 cytotoxic Tcells (CD27-  CD28+)"

interestPercentsM =  melt(interestPercents, id.vars = "Study.ID")
interestPercentsM$KEY = paste0(interestPercentsM$Study.ID, "_", interestPercentsM$variable)
ggplot(interestPercentsM, aes(
  x = reorder(interestPercentsM$variable, value, FUN = median),
  y = value,
  colour = variable
)) +
  xlab(paste0("Population")) +
  ylab(paste0("Percent Parent")) + t2 +
  geom_boxplot() + ggtitle("Manual gating") + ylim(0, 100)


combo = merge(summaries,
              interestPercentsM,
              by.x = "KEY",
              by.y = "KEY")

pops = unique(combo$POPULATION)


corSummary = data.frame()
for (pop in pops) {
  plotData = combo[which(combo$POPULATION == pop), ]
  cor1 = cor.test(
    as.numeric(plotData$PARENT_FREQ),
    as.numeric(plotData$value),
    method = "pearson",
    na.action = "na.omit"
  )
  cor2 = cor.test(
    as.numeric(plotData$PARENT_FREQ),
    as.numeric(plotData$value),
    method = "spearman",
    na.action = "na.omit"
  )
  
  g1 = ggplot(plotData,
              aes(x = PARENT_FREQ,
                  y = value, color = OPTIMAL_K)) +
    geom_point() +
    xlab(paste0("KMEANS percent parent")) +
    ylab(paste0("Manual percent parent")) + t2 + ggtitle(
      paste0(
        pop,
        "\npearson=",
        cor1$estimate,
        "\nspearman=",
        cor2$estimate,
        "\nN=",
        length(plotData$KEY)
      )
    )  +
    theme(legend.position = "bottom")
  
  print(g1)
  
  tmp = data.frame(
    POPULATION = pop,
    METRIC = "PARENT_FREQ",
    PEARSON = cor1$estimate,
    SPEARMAN = cor2$estimate
  )
  corSummary = rbind(corSummary, tmp)
}

write.table(
  corSummary,
  file = corSummaryFile,
  sep = "\t",
  quote = FALSE,
  row.names = FALSE
)



```

